# AXIS-7B-C Docker Publish Workflow

name: Publish AXIS to Docker Hub

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Encrypt
        run: |
          cd AXIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x encrypt_axis.sh && ./encrypt_axis.sh

      - uses: docker/build-push-action@v5
        with:
          context: ./AXIS-7B-C_COMPLETE
          file: ./AXIS-7B-C_COMPLETE/OLLAMA_INTEGRATION/Dockerfile.axis
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quantumfloorai/axis-7b-c:latest
            quantumfloorai/axis-7b-c:${{ github.event.release.tag_name }}
