# AXIS-7B-C GitHub Release Workflow

name: Release AXIS-7B-C

on:
  push:
    tags:
      - 'axis-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install cryptography build

      - name: Encrypt
        run: |
          cd AXIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x encrypt_axis.sh && ./encrypt_axis.sh

      - name: Test speed
        run: |
          cd AXIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x test_speed.sh && ./test_speed.sh

      - name: Build package
        run: |
          cd AXIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x release_package.sh
          ./release_package.sh ${{ github.event.inputs.version || github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            AXIS-7B-C_COMPLETE/dist/*.zip
            AXIS-7B-C_COMPLETE/dist/*.tar.gz
          body: |
            ## AXIS-7B-C Release

            **Size:** 48MB (300x smaller than Llama-7B)
            **Latency:** <20ms selection-to-speech
            **Features:** Hardware accelerated, ultra-fast TTS

            ### Installation
            ```bash
            ollama run quantum-floor-ai/axis-7b-c
            pip install axis-7b-c
            ```
