# REGIS-7B-C Docker Hub Publish Workflow
# Quantum-Floor AI

name: Publish to Docker Hub

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        default: 'latest'

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run encryption
        run: |
          cd REGIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x encrypt_regis.sh
          ./encrypt_regis.sh

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: quantumfloorai/regis-7b-c
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./REGIS-7B-C_COMPLETE
          file: ./REGIS-7B-C_COMPLETE/OLLAMA_INTEGRATION/Dockerfile.regis
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: quantumfloorai/regis-7b-c
          readme-filepath: ./REGIS-7B-C_COMPLETE/DOCUMENTATION/README.md
