# REGIS-7B-C GitHub Release Workflow
# Quantum-Floor AI

name: Release REGIS-7B-C

on:
  push:
    tags:
      - 'regis-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install cryptography build twine

      - name: Run encryption
        run: |
          cd REGIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x encrypt_regis.sh
          ./encrypt_regis.sh

      - name: Run tests
        run: |
          cd REGIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x test_encrypted.sh
          ./test_encrypted.sh

      - name: Build release package
        run: |
          cd REGIS-7B-C_COMPLETE/BUILD_SCRIPTS
          chmod +x release_package.sh
          ./release_package.sh ${{ github.event.inputs.version || github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            REGIS-7B-C_COMPLETE/dist/*.zip
            REGIS-7B-C_COMPLETE/dist/*.tar.gz
          body: |
            ## REGIS-7B-C Release

            **Model Size:** 220MB (64x smaller than Llama-7B)
            **Performance:** Matches Llama-7B quality
            **Features:** 7-level architecture, integrated voice synthesis

            ### Installation

            ```bash
            # Ollama
            ollama run quantum-floor-ai/regis-7b-c

            # Python
            pip install regis-7b-c

            # Docker
            docker run -e REGIS_LICENSE_KEY=<key> -p 11434:11434 quantum-floor-ai/regis-7b-c
            ```

            ### Security Notice
            This distribution is encrypted and protected by quantum lock technology.
            Reverse engineering is prohibited under the commercial license.
          draft: false
          prerelease: false

  publish-docker:
    needs: build-and-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./REGIS-7B-C_COMPLETE
          file: ./REGIS-7B-C_COMPLETE/OLLAMA_INTEGRATION/Dockerfile.regis
          push: true
          tags: |
            quantumfloorai/regis-7b-c:latest
            quantumfloorai/regis-7b-c:${{ github.event.inputs.version || github.ref_name }}
